"use client";

/**
 * The real print/PDF destination for a quotation (linked from the Print
 * button on `/admin/quotations/[id]` and from the list's row actions).
 * Layout/spacing/table structure is modeled on a reference invoice the
 * user supplied (their own TECHNICAL LINE / TIS company invoice); every
 * value shown here is read from existing Quotation/Customer/Store data
 * (Store's company/legal fields were added specifically to hold that
 * real data — see QUOTATION_AUDIT.md §17).
 *
 * Language follows the site's current language by default (single
 * language, no mixing) — the user can switch to "both" with the toggle
 * below to match the reference invoice's bilingual layout exactly.
 *
 * Red is scoped to this document only, per instruction — it does not
 * touch the site's real primary (orange) color anywhere else.
 */

import { useEffect, useState } from "react";
import { ImageOff, ReceiptText } from "lucide-react";

import { formatCurrency, formatDate } from "@/lib/utils";
import type { PreviewQuotation } from "@/components/quotation/preview/to-preview-quotation";

const RED = "#9E2B25";
const RED_DEEP = "#7A1D18";
const RED_TINT = "#F7E9E7";

type Lang = "en" | "ar";
type Mode = Lang | "both";

interface PrintStrings {
  dir: "ltr" | "rtl";
  printBtn: string;
  docTitle: string;
  quotationNo: string;
  issueDate: string;
  validUntil: string;
  client: string;
  walkIn: string;
  columns: {
    item: string;
    description: string;
    image: string;
    qty: string;
    unitPrice: string;
    vat: string;
    total: string;
  };
  noImage: string;
  subtotal: string;
  discount: string;
  vatTotal: string;
  grandTotal: string;
  terms: string;
  notes: string;
  generatedBy: string;
  crLabel: string;
  poBoxLabel: string;
  vatLabel: string;
  mobileLabel: string;
  emailLabel: string;
  langToggle: { en: string; ar: string; both: string };
}

const STRINGS: Record<Lang, PrintStrings> = {
  en: {
    dir: "ltr" as const,
    printBtn: "Print / Save as PDF",
    docTitle: "QUOTATION",
    quotationNo: "Quotation No.",
    issueDate: "Issue Date",
    validUntil: "Valid Until",
    client: "Client",
    walkIn: "Walk-in / Prospect",
    columns: {
      item: "Item",
      description: "Description",
      image: "Product Image",
      qty: "Qty",
      unitPrice: "Unit Price",
      vat: "VAT",
      total: "Total With VAT",
    },
    noImage: "No image",
    subtotal: "Subtotal",
    discount: "Discount",
    vatTotal: "VAT",
    grandTotal: "Total With VAT",
    terms: "Terms & Conditions",
    notes: "Notes",
    generatedBy: "Generated by Hyper POS — this is a quotation, not a tax invoice",
    crLabel: "C.R NO",
    poBoxLabel: "P.O.BOX",
    vatLabel: "VAT No",
    mobileLabel: "Mobile No",
    emailLabel: "Mail",
    langToggle: { en: "English", ar: "Arabic", both: "Both" },
  },
  ar: {
    dir: "rtl" as const,
    printBtn: "طباعة / حفظ كـ PDF",
    docTitle: "عرض سعر",
    quotationNo: "رقم عرض السعر",
    issueDate: "تاريخ الإصدار",
    validUntil: "صالح حتى",
    client: "العميل",
    walkIn: "عميل نقدي / محتمل",
    columns: {
      item: "البند",
      description: "الوصف",
      image: "صورة المنتج",
      qty: "الكمية",
      unitPrice: "سعر الوحدة",
      vat: "الضريبة",
      total: "الإجمالي مع الضريبة",
    },
    noImage: "لا توجد صورة",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    vatTotal: "الضريبة",
    grandTotal: "الإجمالي مع الضريبة",
    terms: "الشروط والأحكام",
    notes: "ملاحظات",
    generatedBy: "تم إنشاؤه بواسطة Hyper POS — هذا عرض سعر وليس فاتورة ضريبية",
    crLabel: "س . ت",
    poBoxLabel: "ص . ب",
    vatLabel: "الرقم الضريبي",
    mobileLabel: "رقم الجوال",
    emailLabel: "البريد الالكتروني",
    langToggle: { en: "الإنجليزية", ar: "العربية", both: "كلاهما" },
  },
};

/** Renders one or both languages for a simple label lookup. In "both" mode,
 * the site's own current language is shown first (bold) with the other
 * stacked below it (muted) — order follows the site's language, not a
 * fixed English/Arabic ordering. */
function trNode(mode: Mode, primaryLang: Lang, pick: (s: PrintStrings) => string) {
  if (mode !== "both") return pick(STRINGS[mode]);
  const secondaryLang: Lang = primaryLang === "en" ? "ar" : "en";
  return (
    <span className="flex flex-col leading-tight">
      <span>{pick(STRINGS[primaryLang])}</span>
      <span className="text-[0.85em] opacity-70">{pick(STRINGS[secondaryLang])}</span>
    </span>
  );
}

function trText(mode: Mode, primaryLang: Lang, pick: (s: PrintStrings) => string) {
  if (mode !== "both") return pick(STRINGS[mode]);
  const secondaryLang: Lang = primaryLang === "en" ? "ar" : "en";
  return `${pick(STRINGS[primaryLang])} / ${pick(STRINGS[secondaryLang])}`;
}

export function QuotationPrintPreview({
  quotation,
  initialLang,
}: {
  quotation: PreviewQuotation;
  initialLang: Lang;
}) {
  // Defaults to the site's current language (single language, no mixing) —
  // the toggle below lets the user switch to a specific language or to
  // "both" (matching the reference invoice's bilingual layout) on demand.
  const [mode, setMode] = useState<Mode>(initialLang);
  const dir = mode === "en" ? "ltr" : "rtl";
  const s = STRINGS[mode === "both" ? initialLang : mode];
  const currencyLocale: Lang = mode === "en" ? "en" : "ar";

  useEffect(() => {
    const timeout = setTimeout(() => window.print(), 150);
    return () => clearTimeout(timeout);
    // Only the initial, site-language render auto-prints — switching the
    // toggle afterwards is a deliberate look-around, not a re-print request.
  }, []);

  const customerName = quotation.customer?.name ?? quotation.prospectName ?? s.walkIn;
  const customerSubline = quotation.customer
    ? [quotation.customer.code, quotation.customer.phone].filter(Boolean).join(" · ")
    : [quotation.prospectPhone, quotation.prospectEmail].filter(Boolean).join(" · ");

  const store = quotation.store;
  const companyName =
    mode === "both" && store.legalNameAr
      ? `${store.legalNameEn ?? store.name} / ${store.legalNameAr}`
      : (mode === "ar" ? store.legalNameAr : store.legalNameEn) ?? store.legalNameEn ?? store.name;

  return (
    <div dir={dir} style={{ fontFamily: "var(--font-geist-sans, sans-serif)" }}>
      {/* Small, unobtrusive controls — the dialog already opened automatically
          on load; these are for reprinting and switching language afterwards. */}
      <div className="no-print fixed end-4 top-4 z-10 flex items-center gap-2">
        <div className="flex overflow-hidden rounded-md border border-neutral-200 bg-white shadow-sm">
          {(["en", "ar", "both"] as const).map((m) => (
            <button
              key={m}
              type="button"
              onClick={() => setMode(m)}
              className="px-2.5 py-1.5 text-xs font-medium"
              style={
                mode === m
                  ? { background: RED, color: "#fff" }
                  : { background: "#fff", color: "#525252" }
              }
            >
              {STRINGS[initialLang].langToggle[m]}
            </button>
          ))}
        </div>
        <button
          type="button"
          onClick={() => window.print()}
          className="rounded-md px-3 py-1.5 text-xs font-semibold text-white shadow-sm"
          style={{ background: RED }}
        >
          {s.printBtn}
        </button>
      </div>

      {/* The document */}
      <div className="flex justify-center bg-neutral-100 px-4 py-8 print:bg-white print:p-0">
        <div
          className="print-sheet w-full max-w-[210mm] bg-white text-neutral-900 shadow-[0_1px_2px_rgba(0,0,0,.06),0_24px_48px_-24px_rgba(40,10,8,.35)] print:shadow-none"
          style={{ padding: "16mm 16mm" }}
        >
          {/* Header: company block one side, doc title other side */}
          <div className="flex items-start justify-between gap-6">
            <div className="flex items-start gap-3">
              <div
                className="flex size-12 shrink-0 items-center justify-center rounded-lg"
                style={{ background: RED }}
              >
                <ReceiptText className="size-6 text-white" />
              </div>
              <div>
                <div className="text-base font-extrabold tracking-tight">{companyName}</div>
                <div className="mt-1 flex flex-col gap-0.5 text-[9px] leading-snug text-neutral-600">
                  {store.crNumber && (
                    <div>
                      {trText(mode, initialLang, (x) => x.crLabel)}: {store.crNumber}
                    </div>
                  )}
                  {store.poBox && (
                    <div>
                      {trText(mode, initialLang, (x) => x.poBoxLabel)}: {store.poBox}
                    </div>
                  )}
                  {(store.countryEn || store.countryAr) && (
                    <div>
                      {mode === "both"
                        ? [store.countryEn, store.countryAr].filter(Boolean).join(" / ")
                        : (mode === "ar" ? store.countryAr : store.countryEn) ?? ""}
                    </div>
                  )}
                  {(store.addressEn || store.addressAr) && (
                    <div>
                      {mode === "both"
                        ? [store.addressEn, store.addressAr].filter(Boolean).join(" / ")
                        : (mode === "ar" ? store.addressAr : store.addressEn) ?? ""}
                    </div>
                  )}
                  {store.vatNumber && (
                    <div>
                      {trText(mode, initialLang, (x) => x.vatLabel)}: {store.vatNumber}
                    </div>
                  )}
                  {store.mobile && (
                    <div>
                      {trText(mode, initialLang, (x) => x.mobileLabel)}: {store.mobile}
                    </div>
                  )}
                  {store.email && (
                    <div>
                      {trText(mode, initialLang, (x) => x.emailLabel)}: {store.email}
                    </div>
                  )}
                </div>
              </div>
            </div>
            <div className="text-end">
              <div className="text-2xl font-extrabold tracking-wide" style={{ color: RED }}>
                {trNode(mode, initialLang, (x) => x.docTitle)}
              </div>
            </div>
          </div>

          {/* Rule */}
          <div className="relative mt-4 mb-5">
            <div className="h-[3px] rounded" style={{ background: RED }} />
            <div className="mt-[3px] h-px bg-neutral-200" />
          </div>

          {/* Meta row: quotation meta + client */}
          <div className="flex justify-between gap-8 border-b border-neutral-200 pb-5">
            <div className="flex flex-col gap-1.5">
              <MetaLine
                label={trText(mode, initialLang, (x) => x.quotationNo)}
                value={quotation.number}
                mono
              />
              <MetaLine
                label={trText(mode, initialLang, (x) => x.issueDate)}
                value={formatDate(quotation.issueDate)}
                mono
              />
              {quotation.validUntil && (
                <MetaLine
                  label={trText(mode, initialLang, (x) => x.validUntil)}
                  value={formatDate(quotation.validUntil)}
                  mono
                />
              )}
            </div>
            <div className="max-w-[55%] text-end">
              <div className="mb-1 text-[10px] font-bold uppercase tracking-wider" style={{ color: RED }}>
                {trNode(mode, initialLang, (x) => x.client)}
              </div>
              <div className="text-sm font-bold">{customerName}</div>
              {customerSubline && (
                <div className="mt-0.5 text-xs text-neutral-500">{customerSubline}</div>
              )}
            </div>
          </div>

          {/* Items table */}
          <table className="mt-5 w-full border-collapse text-xs" style={{ tableLayout: "fixed" }}>
            <colgroup>
              <col style={{ width: "12%" }} />
              <col style={{ width: "26%" }} />
              <col style={{ width: "14%" }} />
              <col style={{ width: "8%" }} />
              <col style={{ width: "13%" }} />
              <col style={{ width: "9%" }} />
              <col style={{ width: "18%" }} />
            </colgroup>
            <thead>
              <tr>
                <Th dir={dir}>{trNode(mode, initialLang, (x) => x.columns.item)}</Th>
                <Th dir={dir}>{trNode(mode, initialLang, (x) => x.columns.description)}</Th>
                <Th dir={dir}>{trNode(mode, initialLang, (x) => x.columns.image)}</Th>
                <Th dir={dir} align="end">
                  {trNode(mode, initialLang, (x) => x.columns.qty)}
                </Th>
                <Th dir={dir} align="end">
                  {trNode(mode, initialLang, (x) => x.columns.unitPrice)}
                </Th>
                <Th dir={dir} align="end">
                  {trNode(mode, initialLang, (x) => x.columns.vat)}
                </Th>
                <Th dir={dir} align="end">
                  {trNode(mode, initialLang, (x) => x.columns.total)}
                </Th>
              </tr>
            </thead>
            <tbody>
              {quotation.items.map((item) => (
                <tr key={item.id} style={{ breakInside: "avoid" }}>
                  <Td className="font-mono text-[10.5px] text-neutral-500">{item.product.sku}</Td>
                  <Td className="font-semibold">{item.product.name}</Td>
                  <Td>
                    {item.product.imageUrl ? (
                      // eslint-disable-next-line @next/next/no-img-element -- fixed-size print thumbnail, must render identically in the PDF/print document.
                      <img
                        src={item.product.imageUrl}
                        alt={item.product.name}
                        width={40}
                        height={40}
                        className="size-10 rounded-md border border-neutral-200 object-cover"
                      />
                    ) : (
                      <div
                        className="flex size-10 items-center justify-center rounded-md border border-dashed border-neutral-300 bg-neutral-50"
                        title={trText(mode, initialLang, (x) => x.noImage)}
                      >
                        <ImageOff className="size-4 text-neutral-300" />
                      </div>
                    )}
                  </Td>
                  <Td align="end" mono>
                    {Number(item.quantity)}
                  </Td>
                  <Td align="end" mono>
                    {formatCurrency(item.unitPrice, currencyLocale)}
                  </Td>
                  <Td align="end" mono>
                    {Number(item.taxRate) > 0 ? `${Number(item.taxRate)}%` : "—"}
                  </Td>
                  <Td align="end" mono className="font-bold">
                    {formatCurrency(item.lineTotal, currencyLocale)}
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Footer: terms/notes + totals */}
          <div className="mt-6 flex items-end justify-between gap-8">
            <div className="max-w-[55%] text-[10px] leading-relaxed text-neutral-500">
              {quotation.termsAndConditions && (
                <div className="mb-2">
                  <div className="mb-0.5 text-[9.5px] font-bold text-neutral-800">
                    {trNode(mode, initialLang, (x) => x.terms)}
                  </div>
                  <div className="whitespace-pre-wrap">{quotation.termsAndConditions}</div>
                </div>
              )}
              {quotation.customerNotes && (
                <div>
                  <div className="mb-0.5 text-[9.5px] font-bold text-neutral-800">
                    {trNode(mode, initialLang, (x) => x.notes)}
                  </div>
                  <div className="whitespace-pre-wrap">{quotation.customerNotes}</div>
                </div>
              )}
            </div>

            <div className="w-[220px] shrink-0">
              <TotalRow
                label={trText(mode, initialLang, (x) => x.subtotal)}
                value={formatCurrency(quotation.subtotal, currencyLocale)}
              />
              {Number(quotation.discountTotal) > 0 && (
                <TotalRow
                  label={trText(mode, initialLang, (x) => x.discount)}
                  value={`− ${formatCurrency(quotation.discountTotal, currencyLocale)}`}
                />
              )}
              <TotalRow
                label={trText(mode, initialLang, (x) => x.vatTotal)}
                value={formatCurrency(quotation.taxTotal, currencyLocale)}
              />
              <div
                className="mt-1.5 flex items-center justify-between rounded-md px-3 py-2 text-sm font-extrabold text-white"
                style={{ background: RED }}
              >
                <span>{trNode(mode, initialLang, (x) => x.grandTotal)}</span>
                <span className="font-mono">{formatCurrency(quotation.total, currencyLocale)}</span>
              </div>
            </div>
          </div>

          <div className="mt-8 border-t border-neutral-200 pt-2.5 text-center text-[9px] tracking-wide text-neutral-400">
            {trText(mode, initialLang, (x) => x.generatedBy)}
          </div>
        </div>
      </div>

      <style>{`
        @media print {
          @page { size: A4; margin: 0; }
          body { background: #fff; }
          * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }
          .print-sheet { box-shadow: none !important; max-width: none !important; }
          table { width: 100%; }
          thead { display: table-header-group; }
          tr { break-inside: avoid; }
        }
      `}</style>
    </div>
  );
}

function MetaLine({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-baseline gap-2 text-xs">
      <span className="font-semibold text-neutral-500">{label}</span>
      <span className={mono ? "font-mono" : ""}>{value}</span>
    </div>
  );
}

function Th({
  children,
  align = "start",
  dir,
}: {
  children: React.ReactNode;
  align?: "start" | "end";
  dir: "ltr" | "rtl";
}) {
  const textAlign =
    align === "end" ? (dir === "rtl" ? "left" : "right") : dir === "rtl" ? "right" : "left";
  return (
    <th
      className="border-b-2 px-2.5 py-2 text-[9.5px] font-extrabold uppercase tracking-wider"
      style={{ background: RED_TINT, color: RED_DEEP, borderColor: RED, textAlign }}
    >
      {children}
    </th>
  );
}

function TotalRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between px-3 py-1 text-xs text-neutral-600">
      <span>{label}</span>
      <span className="font-mono">{value}</span>
    </div>
  );
}

function Td({
  children,
  align = "start",
  mono,
  className = "",
}: {
  children: React.ReactNode;
  align?: "start" | "end";
  mono?: boolean;
  className?: string;
}) {
  return (
    <td
      className={`border-b border-neutral-100 px-2.5 py-2.5 align-middle ${
        align === "end" ? "text-end" : "text-start"
      } ${mono ? "font-mono" : ""} ${className}`}
    >
      {children}
    </td>
  );
}
