"use client";

/**
 * The real print/PDF destination for a quotation (linked from the Print
 * button on `/admin/quotations/[id]` and from the list's row actions).
 * Layout/spacing/table structure is modeled on a reference invoice the
 * user supplied; every value shown here is read from existing
 * Quotation/Customer/Store data — no new database fields, no invented
 * company details. Where the reference showed something we have no field
 * for (company C.R./VAT number, a product photo), it is simply left out
 * rather than faked.
 *
 * Red is scoped to this document only, per instruction — it does not
 * touch the site's real primary (orange) color anywhere else.
 */

import { useEffect } from "react";
import { ImageOff, ReceiptText } from "lucide-react";

import { formatCurrency, formatDate } from "@/lib/utils";
import type { PreviewQuotation } from "@/components/quotation/preview/to-preview-quotation";

const RED = "#9E2B25";
const RED_DEEP = "#7A1D18";
const RED_TINT = "#F7E9E7";

type Lang = "en" | "ar";

const STRINGS = {
  en: {
    dir: "ltr" as const,
    printBtn: "Print / Save as PDF",
    docTitle: "QUOTATION",
    quotationNo: "Quotation No.",
    issueDate: "Issue Date",
    validUntil: "Valid Until",
    client: "Client",
    walkIn: "Walk-in / Prospect",
    columns: {
      item: "Item",
      description: "Description",
      image: "Product Image",
      qty: "Qty",
      unitPrice: "Unit Price",
      vat: "VAT",
      total: "Total With VAT",
    },
    noImage: "No image",
    subtotal: "Subtotal",
    discount: "Discount",
    vatTotal: "VAT",
    grandTotal: "Total With VAT",
    terms: "Terms & Conditions",
    notes: "Notes",
    generatedBy: "Generated by Hyper POS — this is a quotation, not a tax invoice",
  },
  ar: {
    dir: "rtl" as const,
    printBtn: "طباعة / حفظ كـ PDF",
    docTitle: "عرض سعر",
    quotationNo: "رقم عرض السعر",
    issueDate: "تاريخ الإصدار",
    validUntil: "صالح حتى",
    client: "العميل",
    walkIn: "عميل نقدي / محتمل",
    columns: {
      item: "البند",
      description: "الوصف",
      image: "صورة المنتج",
      qty: "الكمية",
      unitPrice: "سعر الوحدة",
      vat: "الضريبة",
      total: "الإجمالي مع الضريبة",
    },
    noImage: "لا توجد صورة",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    vatTotal: "الضريبة",
    grandTotal: "الإجمالي مع الضريبة",
    terms: "الشروط والأحكام",
    notes: "ملاحظات",
    generatedBy: "تم إنشاؤه بواسطة Hyper POS — هذا عرض سعر وليس فاتورة ضريبية",
  },
};

export function QuotationPrintPreview({
  quotation,
  initialLang,
}: {
  quotation: PreviewQuotation;
  initialLang: Lang;
}) {
  // Language always follows the site's current language setting — no manual
  // toggle here, matching "language follows the site's selection" from the
  // original brief. This page is the real print destination now, so it
  // opens straight into the browser's print dialog rather than waiting for
  // an extra click.
  const lang = initialLang;
  const s = STRINGS[lang];
  const dir = s.dir;

  useEffect(() => {
    const timeout = setTimeout(() => window.print(), 150);
    return () => clearTimeout(timeout);
  }, []);

  const customerName = quotation.customer?.name ?? quotation.prospectName ?? s.walkIn;
  const customerSubline = quotation.customer
    ? [quotation.customer.code, quotation.customer.phone].filter(Boolean).join(" · ")
    : [quotation.prospectPhone, quotation.prospectEmail].filter(Boolean).join(" · ");

  return (
    <div dir={dir} lang={lang} style={{ fontFamily: "var(--font-geist-sans, sans-serif)" }}>
      {/* Small, unobtrusive re-print affordance — the dialog above already
          opened automatically, this is only for "print again" after closing it. */}
      <button
        type="button"
        onClick={() => window.print()}
        className="no-print fixed end-4 top-4 z-10 rounded-md px-3 py-1.5 text-xs font-semibold text-white shadow-sm"
        style={{ background: RED }}
      >
        {s.printBtn}
      </button>

      {/* The document */}
      <div className="flex justify-center bg-neutral-100 px-4 py-8 print:bg-white print:p-0">
        <div
          className="print-sheet w-full max-w-[210mm] bg-white text-neutral-900 shadow-[0_1px_2px_rgba(0,0,0,.06),0_24px_48px_-24px_rgba(40,10,8,.35)] print:shadow-none"
          style={{ padding: "16mm 16mm" }}
        >
          {/* Header: brand block one side, doc title other side */}
          <div className="flex items-start justify-between gap-6">
            <div className="flex items-center gap-3">
              <div
                className="flex size-12 shrink-0 items-center justify-center rounded-lg"
                style={{ background: RED }}
              >
                <ReceiptText className="size-6 text-white" />
              </div>
              <div>
                <div className="text-lg font-extrabold tracking-tight">HYPER POS</div>
                <div className="text-xs text-neutral-500">{quotation.store.name}</div>
              </div>
            </div>
            <div className="text-end">
              <div
                className="text-2xl font-extrabold tracking-wide"
                style={{ color: RED }}
              >
                {s.docTitle}
              </div>
            </div>
          </div>

          {/* Rule */}
          <div className="relative mt-4 mb-5">
            <div className="h-[3px] rounded" style={{ background: RED }} />
            <div className="mt-[3px] h-px bg-neutral-200" />
          </div>

          {/* Meta row: quotation meta + client */}
          <div className="flex justify-between gap-8 border-b border-neutral-200 pb-5">
            <div className="flex flex-col gap-1.5">
              <MetaLine label={s.quotationNo} value={quotation.number} mono />
              <MetaLine label={s.issueDate} value={formatDate(quotation.issueDate)} mono />
              {quotation.validUntil && (
                <MetaLine label={s.validUntil} value={formatDate(quotation.validUntil)} mono />
              )}
            </div>
            <div className="max-w-[55%] text-end">
              <div
                className="mb-1 text-[10px] font-bold uppercase tracking-wider"
                style={{ color: RED }}
              >
                {s.client}
              </div>
              <div className="text-sm font-bold">{customerName}</div>
              {customerSubline && (
                <div className="mt-0.5 text-xs text-neutral-500">{customerSubline}</div>
              )}
            </div>
          </div>

          {/* Items table */}
          <table className="mt-5 w-full border-collapse text-xs" style={{ tableLayout: "fixed" }}>
            <colgroup>
              <col style={{ width: "12%" }} />
              <col style={{ width: "28%" }} />
              <col style={{ width: "14%" }} />
              <col style={{ width: "8%" }} />
              <col style={{ width: "13%" }} />
              <col style={{ width: "9%" }} />
              <col style={{ width: "16%" }} />
            </colgroup>
            <thead>
              <tr>
                <Th dir={dir}>{s.columns.item}</Th>
                <Th dir={dir}>{s.columns.description}</Th>
                <Th dir={dir}>{s.columns.image}</Th>
                <Th dir={dir} align="end">
                  {s.columns.qty}
                </Th>
                <Th dir={dir} align="end">
                  {s.columns.unitPrice}
                </Th>
                <Th dir={dir} align="end">
                  {s.columns.vat}
                </Th>
                <Th dir={dir} align="end">
                  {s.columns.total}
                </Th>
              </tr>
            </thead>
            <tbody>
              {quotation.items.map((item) => (
                <tr key={item.id} style={{ breakInside: "avoid" }}>
                  <Td className="font-mono text-[10.5px] text-neutral-500">{item.product.sku}</Td>
                  <Td className="font-semibold">{item.product.name}</Td>
                  <Td>
                    <div
                      className="flex size-10 items-center justify-center rounded-md border border-dashed border-neutral-300 bg-neutral-50"
                      title={s.noImage}
                    >
                      <ImageOff className="size-4 text-neutral-300" />
                    </div>
                  </Td>
                  <Td align="end" mono>
                    {Number(item.quantity)}
                  </Td>
                  <Td align="end" mono>
                    {formatCurrency(item.unitPrice)}
                  </Td>
                  <Td align="end" mono>
                    {Number(item.taxRate) > 0 ? `${Number(item.taxRate)}%` : "—"}
                  </Td>
                  <Td align="end" mono className="font-bold">
                    {formatCurrency(item.lineTotal)}
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Footer: terms/notes + totals */}
          <div className="mt-6 flex items-end justify-between gap-8">
            <div className="max-w-[55%] text-[10px] leading-relaxed text-neutral-500">
              {quotation.termsAndConditions && (
                <div className="mb-2">
                  <div className="mb-0.5 text-[9.5px] font-bold text-neutral-800">{s.terms}</div>
                  <div className="whitespace-pre-wrap">{quotation.termsAndConditions}</div>
                </div>
              )}
              {quotation.customerNotes && (
                <div>
                  <div className="mb-0.5 text-[9.5px] font-bold text-neutral-800">{s.notes}</div>
                  <div className="whitespace-pre-wrap">{quotation.customerNotes}</div>
                </div>
              )}
            </div>

            <div className="w-[220px] shrink-0">
              <TotalRow label={s.subtotal} value={formatCurrency(quotation.subtotal)} />
              {Number(quotation.discountTotal) > 0 && (
                <TotalRow label={s.discount} value={`− ${formatCurrency(quotation.discountTotal)}`} />
              )}
              <TotalRow label={s.vatTotal} value={formatCurrency(quotation.taxTotal)} />
              <div
                className="mt-1.5 flex items-center justify-between rounded-md px-3 py-2 text-sm font-extrabold text-white"
                style={{ background: RED }}
              >
                <span>{s.grandTotal}</span>
                <span className="font-mono">{formatCurrency(quotation.total)}</span>
              </div>
            </div>
          </div>

          <div className="mt-8 border-t border-neutral-200 pt-2.5 text-center text-[9px] tracking-wide text-neutral-400">
            {s.generatedBy}
          </div>
        </div>
      </div>

      <style>{`
        @media print {
          @page { size: A4; margin: 0; }
          body { background: #fff; }
          .print-sheet { box-shadow: none !important; max-width: none !important; }
          table { width: 100%; }
          thead { display: table-header-group; }
          tr { break-inside: avoid; }
        }
      `}</style>
    </div>
  );
}

function MetaLine({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-baseline gap-2 text-xs">
      <span className="font-semibold text-neutral-500">{label}</span>
      <span className={mono ? "font-mono" : ""}>{value}</span>
    </div>
  );
}

function Th({
  children,
  align = "start",
  dir,
}: {
  children: React.ReactNode;
  align?: "start" | "end";
  dir: "ltr" | "rtl";
}) {
  const textAlign =
    align === "end" ? (dir === "rtl" ? "left" : "right") : dir === "rtl" ? "right" : "left";
  return (
    <th
      className="border-b-2 px-2.5 py-2 text-[9.5px] font-extrabold uppercase tracking-wider"
      style={{ background: RED_TINT, color: RED_DEEP, borderColor: RED, textAlign }}
    >
      {children}
    </th>
  );
}

function TotalRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between px-3 py-1 text-xs text-neutral-600">
      <span>{label}</span>
      <span className="font-mono">{value}</span>
    </div>
  );
}

function Td({
  children,
  align = "start",
  mono,
  className = "",
}: {
  children: React.ReactNode;
  align?: "start" | "end";
  mono?: boolean;
  className?: string;
}) {
  return (
    <td
      className={`border-b border-neutral-100 px-2.5 py-2.5 align-middle ${
        align === "end" ? "text-end" : "text-start"
      } ${mono ? "font-mono" : ""} ${className}`}
    >
      {children}
    </td>
  );
}
